import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";

const interFont = Inter({ subsets: ["latin"] });

// ---- farsi font ----
const yekanFont = localFont({
  src: [
    {
      path: "./fonts/YekanBakhFaNum-Regular.ttf",
    },
    {
      path: "./fonts/YekanBakhFaNum-Regular.woff",
    },
  ],
  variable: "--font-yekan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${
          locale === "en" ? interFont.className : yekanFont.variable
        } antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
